services:
  - type: web
    name: social-cause-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://social-75.vercel.app
      - key: PORT
        value: 10000
      - key: DB_NAME
        value: social_cause_prod
